services:
  - type: web
    name: emmpo
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: NODE_VERSION
        value: 20
